apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: q0s7y8jfh-python
  janus-idp.io/tekton: q0s7y8jfh-python
  backstage.io/kubernetes-id: q0s7y8jfh-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q0s7y8jfh-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
