apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: q0s7y8jfh-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: q0s7y8jfh-python 
  name: q0s7y8jfh-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: q0s7y8jfh-python 
